### ISSUE TITLE
Does this work with AMD graphics cards?

### ISSUE THREAD

**Issue by ForgottenLemon** [yum-food/TaSTT#4]
The title is self explanatory, I really want to try this out but I only have an AMD card, do you know if there's even a chance of it working?

**Comment by yum-food** [comment]
You should be able to run this in CPU mode. There's a checkbox on the transcription panel which allows you to enable it.

Fair warning, CPU mode is a lot slower than GPU mode, but should still be usable.

Let me know if you hit any issues!
